name: aiida-gromacs - Lysozyme MD simulation tutorial
category: setup
authors: ""
shortdesc: Data provenance tools demonstrated with Justin Lemkul's lysozyme in water simulation tutorial.
longdesc: ""
