name: tests

on:
  repository_dispatch:
    types: [test]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    name: Testing ${{ github.repository }}
    steps:

    - name: Test notebooks
      shell: bash
      run: |
        docker run -t ghcr.io/${{ github.repository }}:dev bash -c "\
          bash /home/jovyan/aiida-start; \
          find . -name '*.ipynb' | jupyter nbconvert --to notebook --execute lysozyme_tutorial.ipynb; \
          sleep 2; \
          verdi process list -a; \
          ! verdi process list -a | grep -E '\[(3.*?)\]'; \
          ! verdi process list -a | grep -E 'Waiting'; "

    - name: Authenticate with GHCR
      id: ghcr-auth
      uses: docker/login-action@v3.4.0
      with:
        registry: "ghcr.io"
        username: ${{github.actor}}
        password: ${{secrets.BUILD_TOKEN}}

    - name: Push new tags
      shell: bash
      run: |
        docker buildx imagetools create \
          --tag ghcr.io/${{ github.repository }}:latest \
          --tag ghcr.io/${{ github.repository }}:${{ github.event.client_payload.tag }} \
          ghcr.io/${{ github.repository }}:dev
